VehicleDictionary = {
    ["Police Department"] = {
        { id = "11cvpi", value = "CVPI" },
        { id = "11imp", value = "Impala" },
        { id = "18tau", value = "Taurus 2018" },
        { id = "20charg", value = "Charger 2020" },
        { id = "20dur", value = "Durango 2020" },
        { id = "20fpiu", value = "FPIU 2020" },
        { id = "24mus", value = "Mustang 2024" },
        { id = "2016ram", value = "Ram 2016" },
        { id = "2018f150", value = "F150 2018" },
        { id = "2019gmc", value = "GMC 2019" },
        { id = "2022tahoe", value = "Tahoe 2022" },
        { id = "11cvpislick", value = "CVPI Slicktop 2011" },
        { id = "11impslick", value = "Impala Slicktop 2011" },
        { id = "18tauslick", value = "Taurus Slicktop 2018" },
        { id = "20chargslick", value = "Charger Slicktop 2020" },
        { id = "20durslick", value = "Durango Slicktop 2020" },
        { id = "20fpiuslick", value = "FPIU Slicktop 2020" },
        { id = "24musslick", value = "Mustang Slicktop 2024" },
        { id = "2016ramslick", value = "Ram Slicktop 2016" },
        { id = "2018f150slick", value = "F150 Slicktop 2018" },
        { id = "2019gmcslick", value = "GMC Slicktop 2019" },
        { id = "2022tahoeslick", value = "Tahoe Slicktop 2022" }
    },
    ["Sheriff's Office"] = {
        { id = "sast1", value = "SAST 1" },
        { id = "sast2", value = "SAST 2" },
        { id = "sast3", value = "SAST 3" },
        { id = "sast4", value = "SAST 4" },
        { id = "sast5", value = "SAST 5" },
        { id = "sast6", value = "SAST 6" },
        { id = "sast7", value = "SAST 7" },
        { id = "sast8", value = "SAST 8" },
        { id = "sast9", value = "SAST 9" },
        { id = "sast10", value = "SAST 10" },
        { id = "sast11", value = "SAST 11" },
        { id = "sast12", value = "SAST 12" },
        { id = "sast13", value = "SAST 13" }
    },
    ["EMS"] = {
        { id = "enforcer", value = "Enforcer" },
        { id = "enforcerf", value = "Enforcer Fire" },
        { id = "enforcerta", value = "Enforcer TA" },
        { id = "enladder", value = "Ladder Truck" },
        { id = "21silvhd", value = "Silverado HD 2021" },
        { id = "bulldog", value = "Bulldog" },
        { id = "skidfiref350", value = "Skid Fire F350" },
        { id = "firechgr", value = "Fire Charger" },
        { id = "firef350", value = "Fire F350" },
        { id = "fireram", value = "Fire Ram" },
        { id = "firetaurus", value = "Fire Taurus" }
    }
}
